import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Strata',
  description: 'Terms of service for Strata — the trust layer for AI agents.',
}

const sections: { title: string; content: React.ReactNode }[] = [
  {
    title: '1. Acceptance of Terms',
    content: (
      <p>
        By accessing or using the Strata API (&ldquo;Service&rdquo;), you agree to be bound by these
        Terms of Service. If you do not agree, do not use the Service.
      </p>
    ),
  },
  {
    title: '2. Disclaimer of Warranties',
    content: (
      <p>
        The Service is provided &ldquo;as is&rdquo; without warranties of any kind, express or
        implied, including but not limited to warranties of merchantability, fitness for a particular
        purpose, or non-infringement.
      </p>
    ),
  },
  {
    title: '3. API Keys and Account Security',
    content: (
      <p>
        You are responsible for maintaining the security of your API key. Do not share your key or
        expose it in client-side code. You are responsible for all activity that occurs under your
        key. Notify us immediately at{' '}
        <a href="mailto:support@usestrata.dev" className="footer-link" style={{ color: 'var(--ink-soft)' }}>
          support@usestrata.dev
        </a>{' '}
        if you believe your key has been compromised.
      </p>
    ),
  },
  {
    title: '4. Acceptable Use',
    content: (
      <>
        <p style={{ marginBottom: 14 }}>You may not use the Service to:</p>
        <ul style={{ paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
          <li>Violate any applicable laws or regulations</li>
          <li>Attempt to reverse engineer or circumvent rate limits</li>
          <li>Resell or redistribute access to the Service without permission</li>
          <li>
            Use the Service to train machine learning models without express written permission
          </li>
        </ul>
      </>
    ),
  },
  {
    title: '5. Rate Limits and Service Tiers',
    content: (
      <p>
        Free tier accounts are limited to 100 API calls per month. Pro tier accounts are limited to
        10,000 API calls per month. Limits reset monthly. Exceeding limits will result in a 429
        response. We reserve the right to modify limits at any time.
      </p>
    ),
  },
  {
    title: '6. Payment and Billing',
    content: (
      <p>
        Pro subscriptions are billed monthly via Stripe. You may cancel at any time. Refunds are
        handled at our discretion. Prices may change with 30 days notice.
      </p>
    ),
  },
  {
    title: '7. Community Submissions',
    content: (
      <p>
        By submitting content to Strata, you grant us a non-exclusive, worldwide, royalty-free
        license to use, display, and distribute your submission as part of the Service. You represent
        that you have the right to submit the content and that it does not infringe any third party
        rights.
      </p>
    ),
  },
  {
    title: '8. Intellectual Property',
    content: (
      <p>
        The Service, including all content generated by Strata, is owned by Parnell Thrower doing
        business as Strata. You may not copy, modify, or distribute any part of the Service without
        permission.
      </p>
    ),
  },
  {
    title: '9. Limitation of Liability',
    content: (
      <p>
        To the maximum extent permitted by law, Strata shall not be liable for any indirect,
        incidental, special, or consequential damages. Our total liability shall not exceed the
        amount you paid in the last 12 months.
      </p>
    ),
  },
  {
    title: '10. Termination',
    content: (
      <p>
        We reserve the right to suspend or terminate your account at any time for violation of these
        terms or for any other reason at our discretion.
      </p>
    ),
  },
  {
    title: '11. Changes to Terms',
    content: (
      <p>
        We may update these terms at any time. Continued use of the Service after changes constitutes
        acceptance.
      </p>
    ),
  },
  {
    title: '12. Contact',
    content: (
      <p>
        Questions about these terms:{' '}
        <a href="mailto:support@usestrata.dev" className="footer-link" style={{ color: 'var(--ink-soft)' }}>
          support@usestrata.dev
        </a>
      </p>
    ),
  },
]

export default function TermsPage() {
  return (
    <article style={{ maxWidth: 672, margin: '0 auto', padding: '80px 0 64px' }}>
      <h1 style={{
        fontFamily: 'var(--font-serif)', fontSize: 48, fontWeight: 500,
        letterSpacing: '-0.025em', lineHeight: 1.08,
        color: 'var(--ink)', margin: '0 0 10px',
      }}>
        Terms of Service
      </h1>
      <p style={{
        fontFamily: 'var(--font-mono)', fontSize: 12, letterSpacing: '0.08em',
        color: 'var(--ink-faint)', margin: '0 0 64px',
      }}>
        Effective April 29, 2026
      </p>

      {sections.map(({ title, content }) => (
        <section key={title} style={{ marginBottom: 44 }}>
          <h2 style={{
            fontFamily: 'var(--font-serif)', fontSize: 20, fontWeight: 400,
            letterSpacing: '-0.01em', color: 'var(--ink)', margin: '0 0 14px',
          }}>
            {title}
          </h2>
          <div style={{ color: 'var(--ink-soft)', lineHeight: 1.75, fontSize: 15 }}>
            {content}
          </div>
        </section>
      ))}
    </article>
  )
}
